=== ArisMitentzis/toulisShop/xml/aboutOrders.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT aboutOrders (allOrders,popProducts)>
<!ELEMENT allOrders (order*)>
<!ELEMENT order (orderCode,lastName,firstName,totalValue)>
<!ELEMENT orderCode (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT totalValue (#PCDATA)>
<!ELEMENT popProducts (product*)>
<!ELEMENT product (prodCode,prodName,totalSoldQuantity)>
<!ELEMENT prodCode (#PCDATA)>
<!ELEMENT prodName (#PCDATA)>
<!ELEMENT totalSoldQuantity (#PCDATA)>

<!ATTLIST aboutOrders dateFrom CDATA #IMPLIED>
<!ATTLIST aboutOrders dateTo CDATA #IMPLIED>

=== ArisMitentzis/toulisShop/xml/allOrdersAndTop5SalesProducts20201024140309.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aboutOrders SYSTEM "aboutOrders.dtd">
<aboutOrders dateFrom="17-10-2020" dateTo="24-10-2020">
  <allOrders>
    <order>
      <orderCode>66</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>4.05</totalValue>
    </order>
    <order>
      <orderCode>67</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>2.1</totalValue>
    </order>
  </allOrders>
  <popProducts>
    <product>
      <prodCode>22</prodCode>
      <prodName>Σκυλοπαιχνίδι Σκαντζόχοιρος</prodName>
      <totalSoldQuantity>3</totalSoldQuantity>
    </product>
    <product>
      <prodCode>24</prodCode>
      <prodName>Skylo-news</prodName>
      <totalSoldQuantity>1</totalSoldQuantity>
    </product>
  </popProducts>
</aboutOrders>

=== ArisMitentzis/toulisShop/xml/allOrdersAndTop5SalesProducts20201025182031.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aboutOrders SYSTEM "aboutOrders.dtd">
<aboutOrders dateFrom="18-10-2020" dateTo="25-10-2020">
  <allOrders>
    <order>
      <orderCode>68</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>66</orderCode>
      <lastName>Τσαλτιδης</lastName>
      <firstName>Τακης</firstName>
      <totalValue>4.05</totalValue>
    </order>
    <order>
      <orderCode>67</orderCode>
      <lastName>Τσαλτιδης</lastName>
      <firstName>Τακης</firstName>
      <totalValue>2.1</totalValue>
    </order>
  </allOrders>
  <popProducts>
    <product>
      <prodCode>22</prodCode>
      <prodName>Σκυλοπαιχνίδι Σκαντζόχοιρος</prodName>
      <totalSoldQuantity>4</totalSoldQuantity>
    </product>
    <product>
      <prodCode>23</prodCode>
      <prodName>Mocdog</prodName>
      <totalSoldQuantity>2</totalSoldQuantity>
    </product>
    <product>
      <prodCode>24</prodCode>
      <prodName>Skylo-news</prodName>
      <totalSoldQuantity>2</totalSoldQuantity>
    </product>
  </popProducts>
</aboutOrders>

=== ArisMitentzis/toulisShop/xml/allOrdersAndTop5SalesProducts20201024154926.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aboutOrders SYSTEM "aboutOrders.dtd">
<aboutOrders dateFrom="24-01-2020" dateTo="24-10-2020">
  <allOrders>
    <order>
      <orderCode>55</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>228.7</totalValue>
    </order>
    <order>
      <orderCode>42</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>153.1</totalValue>
    </order>
    <order>
      <orderCode>44</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>106.2</totalValue>
    </order>
    <order>
      <orderCode>63</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>93.9</totalValue>
    </order>
    <order>
      <orderCode>28</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>90.7</totalValue>
    </order>
    <order>
      <orderCode>48</orderCode>
      <lastName>Προβίδης</lastName>
      <firstName>Μιχάλης</firstName>
      <totalValue>89</totalValue>
    </order>
    <order>
      <orderCode>32</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>87.7</totalValue>
    </order>
    <order>
      <orderCode>56</orderCode>
      <lastName>Προβίδης</lastName>
      <firstName>Μιχάλης</firstName>
      <totalValue>86.9</totalValue>
    </order>
    <order>
      <orderCode>25</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>75.6</totalValue>
    </order>
    <order>
      <orderCode>29</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>69.1</totalValue>
    </order>
    <order>
      <orderCode>59</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>64.8</totalValue>
    </order>
    <order>
      <orderCode>61</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>51.9</totalValue>
    </order>
    <order>
      <orderCode>35</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>42.55</totalValue>
    </order>
    <order>
      <orderCode>23</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>41.4</totalValue>
    </order>
    <order>
      <orderCode>45</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>39</totalValue>
    </order>
    <order>
      <orderCode>64</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>38.25</totalValue>
    </order>
    <order>
      <orderCode>40</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>36.1</totalValue>
    </order>
    <order>
      <orderCode>58</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>33</totalValue>
    </order>
    <order>
      <orderCode>51</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>29.4</totalValue>
    </order>
    <order>
      <orderCode>33</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>26.2</totalValue>
    </order>
    <order>
      <orderCode>65</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>49</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>53</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>24.7</totalValue>
    </order>
    <order>
      <orderCode>46</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>21.7</totalValue>
    </order>
    <order>
      <orderCode>57</orderCode>
      <lastName>Προβίδης</lastName>
      <firstName>Μιχάλης</firstName>
      <totalValue>19.8</totalValue>
    </order>
    <order>
      <orderCode>24</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>19.7</totalValue>
    </order>
    <order>
      <orderCode>47</orderCode>
      <lastName>Προβίδης</lastName>
      <firstName>Μιχάλης</firstName>
      <totalValue>15.9</totalValue>
    </order>
    <order>
      <orderCode>31</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>15.7</totalValue>
    </order>
    <order>
      <orderCode>37</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>15.1</totalValue>
    </order>
    <order>
      <orderCode>26</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>13.6</totalValue>
    </order>
    <order>
      <orderCode>52</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>13.1</totalValue>
    </order>
    <order>
      <orderCode>27</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>13</totalValue>
    </order>
    <order>
      <orderCode>34</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>13</totalValue>
    </order>
    <order>
      <orderCode>43</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>11</totalValue>
    </order>
    <order>
      <orderCode>60</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>7</totalValue>
    </order>
    <order>
      <orderCode>62</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>6.15</totalValue>
    </order>
    <order>
      <orderCode>39</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>4.9</totalValue>
    </order>
    <order>
      <orderCode>54</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>4.8</totalValue>
    </order>
    <order>
      <orderCode>66</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>4.05</totalValue>
    </order>
    <order>
      <orderCode>30</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>2.1</totalValue>
    </order>
    <order>
      <orderCode>36</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>2.1</totalValue>
    </order>
    <order>
      <orderCode>67</orderCode>
      <lastName>Takos</lastName>
      <firstName>Takis</firstName>
      <totalValue>2.1</totalValue>
    </order>
    <order>
      <orderCode>38</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>1.35</totalValue>
    </order>
    <order>
      <orderCode>41</orderCode>
      <lastName>Χιωλικιδης</lastName>
      <firstName>Δημος</firstName>
      <totalValue>1.35</totalValue>
    </order>
  </allOrders>
  <popProducts>
    <product>
      <prodCode>23</prodCode>
      <prodName>Mocdog</prodName>
      <totalSoldQuantity>42</totalSoldQuantity>
    </product>
    <product>
      <prodCode>22</prodCode>
      <prodName>Σκυλοπαιχνίδι Σκαντζόχοιρος</prodName>
      <totalSoldQuantity>32</totalSoldQuantity>
    </product>
    <product>
      <prodCode>24</prodCode>
      <prodName>Skylo-news</prodName>
      <totalSoldQuantity>17</totalSoldQuantity>
    </product>
    <product>
      <prodCode>16</prodCode>
      <prodName>Mini sticks</prodName>
      <totalSoldQuantity>15</totalSoldQuantity>
    </product>
    <product>
      <prodCode>21</prodCode>
      <prodName>Σκυλοπαιχνίδι Καρδιά</prodName>
      <totalSoldQuantity>14</totalSoldQuantity>
    </product>
  </popProducts>
</aboutOrders>

=== ArisMitentzis/toulisShop/xml/allOrdersAndTop5SalesProducts20210531152557.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aboutOrders SYSTEM "aboutOrders.dtd">
<aboutOrders dateFrom="24-05-2021" dateTo="31-05-2021">
  <allOrders>
    <order>
      <orderCode>81</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>14.5</totalValue>
    </order>
  </allOrders>
  <popProducts>
    <product>
      <prodCode>19</prodCode>
      <prodName>Φτηνο-κολαρέξ</prodName>
      <totalSoldQuantity>4</totalSoldQuantity>
    </product>
    <product>
      <prodCode>17</prodCode>
      <prodName>Πουλοβερεξ Σκύλου</prodName>
      <totalSoldQuantity>1</totalSoldQuantity>
    </product>
  </popProducts>
</aboutOrders>

=== ArisMitentzis/toulisShop/xml/allOrdersAndTop5SalesProducts20210530162603.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aboutOrders SYSTEM "aboutOrders.dtd">
<aboutOrders dateFrom="23-05-2021" dateTo="30-06-2021">
  <allOrders>
    <order>
      <orderCode>80</orderCode>
      <lastName>Τσαλτιδης</lastName>
      <firstName>Τακης</firstName>
      <totalValue>57.4</totalValue>
    </order>
  </allOrders>
  <popProducts>
    <product>
      <prodCode>18</prodCode>
      <prodName>Τουμπανοκροκέτες (4kg)</prodName>
      <totalSoldQuantity>2</totalSoldQuantity>
    </product>
  </popProducts>
</aboutOrders>

=== ArisMitentzis/toulisShop/xml/allOrdersAndTop5SalesProducts20201025182050.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aboutOrders SYSTEM "aboutOrders.dtd">
<aboutOrders dateFrom="18-10-2020" dateTo="26-10-2020">
  <allOrders>
    <order>
      <orderCode>73</orderCode>
      <lastName>Γατου</lastName>
      <firstName>Στεφανια</firstName>
      <totalValue>145.9</totalValue>
    </order>
    <order>
      <orderCode>76</orderCode>
      <lastName>Σουγιας</lastName>
      <firstName>Μπαμπης</firstName>
      <totalValue>122.8</totalValue>
    </order>
    <order>
      <orderCode>78</orderCode>
      <lastName>Σουγιας</lastName>
      <firstName>Μπαμπης</firstName>
      <totalValue>81.05</totalValue>
    </order>
    <order>
      <orderCode>70</orderCode>
      <lastName>Κοκωνης</lastName>
      <firstName>Στελιος</firstName>
      <totalValue>59.2</totalValue>
    </order>
    <order>
      <orderCode>72</orderCode>
      <lastName>Κοκωνης</lastName>
      <firstName>Στελιος</firstName>
      <totalValue>53.5</totalValue>
    </order>
    <order>
      <orderCode>79</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>69</orderCode>
      <lastName>Τσαλτιδης</lastName>
      <firstName>Τακης</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>68</orderCode>
      <lastName>Πεκος</lastName>
      <firstName>Γιώργος</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>74</orderCode>
      <lastName>Γατου</lastName>
      <firstName>Στεφανια</firstName>
      <totalValue>25.45</totalValue>
    </order>
    <order>
      <orderCode>71</orderCode>
      <lastName>Κοκωνης</lastName>
      <firstName>Στελιος</firstName>
      <totalValue>16.4</totalValue>
    </order>
    <order>
      <orderCode>75</orderCode>
      <lastName>Γατου</lastName>
      <firstName>Στεφανια</firstName>
      <totalValue>10.85</totalValue>
    </order>
    <order>
      <orderCode>66</orderCode>
      <lastName>Τσαλτιδης</lastName>
      <firstName>Τακης</firstName>
      <totalValue>4.05</totalValue>
    </order>
    <order>
      <orderCode>67</orderCode>
      <lastName>Τσαλτιδης</lastName>
      <firstName>Τακης</firstName>
      <totalValue>2.1</totalValue>
    </order>
    <order>
      <orderCode>77</orderCode>
      <lastName>Σουγιας</lastName>
      <firstName>Μπαμπης</firstName>
      <totalValue>2.1</totalValue>
    </order>
  </allOrders>
  <popProducts>
    <product>
      <prodCode>23</prodCode>
      <prodName>Mocdog</prodName>
      <totalSoldQuantity>15</totalSoldQuantity>
    </product>
    <product>
      <prodCode>22</prodCode>
      <prodName>Σκυλοπαιχνίδι Σκαντζόχοιρος</prodName>
      <totalSoldQuantity>11</totalSoldQuantity>
    </product>
    <product>
      <prodCode>24</prodCode>
      <prodName>Skylo-news</prodName>
      <totalSoldQuantity>7</totalSoldQuantity>
    </product>
    <product>
      <prodCode>10</prodCode>
      <prodName>Σκυλο-Μπαλάκι</prodName>
      <totalSoldQuantity>7</totalSoldQuantity>
    </product>
    <product>
      <prodCode>13</prodCode>
      <prodName>Redneck</prodName>
      <totalSoldQuantity>6</totalSoldQuantity>
    </product>
  </popProducts>
</aboutOrders>
